modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/MrUnknown404/SlabGen/issues"

[[mods]]
modId="slabgen"
version="1.1.0"
displayName="SlabGen"
displayURL="https://github.com/MrUnknown404/SlabGen"
#logoFile="examplemod.png"
credits=""
authors="-Unknown-"
description='''
Adds Dirt/Grass slabs to World Gen
'''

[[dependencies.slabgen]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.slabgen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"